#!/bin/sh
# Generates <mod-root>/kristal-lib-globals.lua from the mod's libraries/.
#
# Libraries register their globals in two ways at runtime:
#   1. libraries/<lib>/lib.lua 中 Registry.registerGlobal("Name", lib)
#   2. libraries/<lib>/scripts/globals/*.lua 的返回值（文件名即全局名）
# Both become real _G globals; this script writes a LuaLS shim that declares
# each one via a path-style require, so mod code (and library code) no longer
# reports undefined-global for them.
#
# Rerun after adding/removing libraries or changing their globals, then
# commit the generated file.
set -eu

script_path=$0
case "$script_path" in
  */*) ;;
  *)
    script_path=$(command -v "$script_path") || {
      echo "cannot locate script: $0" >&2
      exit 1
    }
    ;;
esac

script_dir=$(CDPATH= cd "$(dirname "$script_path")" && pwd -P)
mod_root=$(CDPATH= cd "$script_dir/../.." && pwd -P)
libs_dir="$mod_root/libraries"
out_file="$mod_root/kristal-lib-globals.lua"

if [ ! -d "$libs_dir" ]; then
  echo "no libraries directory: $libs_dir" >&2
  exit 1
fi

tmp_file="$mod_root/.kristal-lib-globals.lua.tmp"
trap 'rm -f "$tmp_file"' EXIT

# --- Collect globals: Name<tab>require-path, deduped, sorted ---
{
  # 1. Registry.registerGlobal("Name", ...) in lib.lua
  for lib in "$libs_dir"/*/; do
    [ -d "$lib" ] || continue
    lib_id=$(basename "$lib")
    [ -f "$lib/lib.lua" ] || continue
    sed -n 's/.*registerGlobal([[:space:]]*"\([^"]*\)".*/\1\tlibraries\/'"$lib_id"'\/lib/p' "$lib/lib.lua"
  done

  # 2. scripts/globals/*.lua (recursive): file basename is the global id.
  for globals_file in "$libs_dir"/*/scripts/globals/*.lua; do
    [ -f "$globals_file" ] || continue
    lib_id=$(basename "$(dirname "$(dirname "$(dirname "$globals_file")")")")
    name=$(basename "$globals_file" .lua)
    printf '%s\tlibraries/%s/scripts/globals/%s\n' \
      "$name" "$lib_id" "$(basename "$globals_file")"
  done
} | sort -u > "$tmp_file"

if [ ! -s "$tmp_file" ]; then
  echo "no library globals found under: $libs_dir" >&2
  exit 1
fi

{
  cat <<'EOF'
-- Library globals, generated by tools/gen-lib-globals.sh. Do not edit by hand.
--
-- These names are not defined by this mod: each library registers them as
-- real Lua globals at runtime (Registry.registerGlobal, or a scripts/globals
-- script whose return value the Registry publishes), so mod code can use them
-- bare, matching the Kristal library semantics. This file only teaches LuaLS
-- about those globals; each require is path-style so LuaLS resolves it
-- straight to the library source file.
EOF
  while IFS=$(printf '\t') read -r name require_path; do
    printf '%s\n' ''
    printf '%s\n' '---@diagnostic disable-next-line: undefined-global'
    printf '%s = require("%s")\n' "$name" "$require_path"
  done < "$tmp_file"
} > "$out_file"

echo "generated $out_file"
sed 's/^/  /' "$tmp_file"
